### PR TITLE
refactor: expose auto form event types

### PR DESCRIPTION
**Pull request by sissbruecker**
Expose event types for auto form so they can be imported by the application.

### CODE REVIEW

**Review by taefi — DISMISSED** [review]

**Review by cromoteca — CHANGES_REQUESTED** [review]
Requesting changes to make sure we choose between this one and https://github.com/vaadin/hilla/pull/1717

**Comment by sissbruecker** [comment]
@cromoteca Well they do different things. This PR exposes event types, while your PR improves error handling. But feel free to adopt the changes here in your PR.

**Comment by cromoteca** [comment]
But are you sure that exposing those types is needed?

**Comment by sissbruecker** [comment]
I think so, see the changes in `AutoFormView.tsx` in this PR. Basically if you want to extract your submit or error handler into a standalone function then you need to declare the parameter type somehow.

**Comment by cromoteca** [comment]
Merged `main` manually

**Review by taefi — APPROVED** [review]

**Review by cromoteca — APPROVED** [review]

**Pull request merged**
