### PR TITLE
feat: add support for JsonSubTypes

### LINKED ISSUE #438: Support polymorphic return types through @JsonSubTypes
When sending different types of events to the client, I want to be able to use one Flux endpoint method for all different types of events as they are happening in a logical order that I want to preserve. On the client side I want to be able to differentiate between the event types and handle them separately.

**Describe the solution you'd like**

Ideally I would want to define my endpoint method to return an abstract type, e.g.
```
public Flux<AbstractEvent> subscribe() { ... }
```
and nothing else. This does not seem realistic as Hilla then would need to find out all possible subtypes of `AbstractEvent`. While it can work for a limited case it would not work very well if returning `Flux<Object>`. Also with only this there is no information available on the client side about which type of event was actually sent, unless the event instance manually include that data.

Jackson supports `@JsonSubTypes` which should help here for both of the problems. If I annotate my `AbstractEvent` as
```
    @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = AddEvent.class, name = "add"),
            @JsonSubTypes.Type(value = UpdateEvent.class, name = "update"),
            @JsonSubTypes.Type(value = DeleteEvent.class, name = "delete") })
```
then 
1. Hilla should generate TS for all the mentioned sub types: `AddEvent`, `UpdateEvent`, `DeleteEvent`
2. Jackson will add the `@type` property (because of use=`NAME`) when serializing so you can distinguish the event types on the client side
3. Hilla should include the `@type` property in the generated TS to make it easy to access

### LINKED ISSUE #1255: Support @JsonSubType for method parameters
**Is your feature request related to a problem? Please describe.**
This is a smaller part extracted from #438.

When you have an interface such as 
```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "t")
@JsonSubTypes({ @Type(value = OrFilter.class, name = "o"),
        @Type(value = AndFilter.class, name = "a"),
        @Type(value = PropertyStringFilter.class, name = "p") })
public interface Filter {

}
```

and you use the interface e.g. as a method parameter
```
    public List<Person> list(Pageable pageable, @Nullable Filter filter) {
```

Then TS files for `OrFilter`, `AndFilter` and `PropertyStringFilter` should be generated and the generated files should contain the appropriate "type" field, which depends on the JsonSubType annotation values

### PR DESCRIPTION
**Pull request by cromoteca**
Adds a union type for JsonSubTypes.

This is the supported configuration:

```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY)
@JsonSubTypes({
    @JsonSubTypes.Type(value = UpFilter.class, name = "Up"),
    @JsonSubTypes.Type(value = DownFilter.class, name = "Down")}
)
public class Filter {
    public int dummy;
}
```

Closes #438
Closes #1255

### CODE REVIEW

**Comment by Artur-** [comment]
This is what I see from the `react-grid-test` module
```
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.mappedtypes.PageableUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.crud.filter.Filter'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.test.reactgrid.CompanyUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.test.reactgrid.PersonUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.mappedtypes.SortUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.crud.filter.PropertyStringFilter$MatcherUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' dev.hilla.mappedtypes.OrderUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' org.springframework.data.domain.Sort$DirectionUnion'
WARN (tsgen) <BackbonePlugin>: Component has no properties:' org.springframework.data.domain.Sort$NullHandlingUnion'
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.mappedtypes.PageableUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.crud.filter.Filter
ERROR (tsgen) <ModelPlugin>: The schema for a class component dev.hilla.crud.filter.FilterUnion is broken.
    type: "object"
    oneOf: [
      {
        "$ref": "#/components/schemas/dev.hilla.crud.filter.OrFilter"
      },
      {
        "$ref": "#/components/schemas/dev.hilla.crud.filter.AndFilter"
      },
      {
        "$ref": "#/components/schemas/dev.hilla.crud.filter.PropertyStringFilter"
      }
    ]
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.test.reactgrid.CompanyUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.test.reactgrid.PersonUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.mappedtypes.SortUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.crud.filter.PropertyStringFilter$MatcherUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: dev.hilla.mappedtypes.OrderUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: org.springframework.data.domain.Sort$DirectionUnion
WARN (tsgen) <ModelPlugin>: Component has no properties: org.springframework.data.domain.Sort$NullHandlingUnion
```

and then it fails with
```
[ERROR] frontend/generated/dev/hilla/crud/filter/FilterUnionModel.ts(3,16): error TS2304: Cannot find name 'FilterUnionModel'.
```

```
% cat frontend/generated/dev/hilla/crud/filter/FilterUnionModel.ts 
import { _getPropertyModel as _getPropertyModel_1 } from "@hilla/form";
import type FilterUnion_1 from "./FilterUnion.js";
export default FilterUnionModel;
```

**Comment by cromoteca** [comment]
You tried too fast ;)

**Review by Lodin — DISMISSED** [review]
LGTM

**Comment by Lodin** [comment]
BTW, is it gonna be supported by `EndpointInvoker` runtime?

**Comment by cromoteca** [comment]
> BTW, is it gonna be supported by `EndpointInvoker` runtime?

What support should be added? You'll send normal types anyway, never the union. It doesn't exist in Java.

**Comment by Lodin** [comment]
Yeah, I noticed that `@type` is not used by the model, so I was wondering about how it is supported on the Java end.

**Review by Lodin — APPROVED** [review]

**Pull request merged**
