### PR TITLE
refactor: Do not use installAutoSignalTracking

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by Artur-** [comment]
Depends on https://github.com/vaadin/flow/pull/19639

**Comment by Artur-** [comment]
With the Flow PR, at least `react-i18n` and `react-signals` pass locally

**Comment by Artur-** [comment]
Maybe there is a better way with Karma to add
```
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
```

The "correct" way would be to pass the HTML files through Vite but I don't see how that would be possible

**Review by platosha — COMMENTED** [review]
Using custom Karma HTML is OK to me. @Lodin WDYT?

**Review by Lodin — APPROVED** [review]
Looks a bit hacky to me but let's have it this way. I hope we will be able to solve it easier in #2480

**Pull request merged**
