### PR TITLE
fix(endpoint): websocket path matching is not matching because of trailing slash

### PR DESCRIPTION
**Pull request by rob-64**
old fusion-endpoint had trailing slash

## Description

Please list all relevant dependencies in this section and provide summary of the change, motivation and context.

Fixes # (issue)

## Type of change

- [x] Bugfix
- [ ] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [ ] I have added a description following the guideline.
- [ ] The issue is created in the corresponding repository and I have referenced it.
- [ ] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [ ] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by Artur-** [comment]
What is it not matching?

**Comment by rob-64** [comment]
The websocket handler doesn't get activated on the http request because the path the browser sends ends with a/but the registration doesn't so it always falls back to pulling instead of web socket

**Comment by Artur-** [comment]
At least the path here https://github.com/vaadin/hilla/blob/1.2/packages/ts/hilla-frontend/src/FluxConnection.ts#L51 does not use a trailing slash either

**Comment by Artur-** [comment]
Seems like socket.io ALWAYS appends a `/` to the path...

**Comment by rob-64** [comment]
Yea. So I couldn't get a web socket with reactive end points until I double registered it with the trailing slash

**Review by platosha — APPROVED** [review]

**Review by platosha — APPROVED** [review]

**Pull request merged**
