### PR TITLE
feat: use Spring Validator when available

### LINKED ISSUE #964: Autowiring in Validators in Hilla Endpoint DTO Validation
### Description of the bug 
When annotating a DTO which is submitted to an Endpoint with a Custom Constraint Validator that DTO is validated by dev.hilla.EndpointInvoker#validator. That works as expected. If that Validator has an @Autowire dependency it is not resolved and is therefore null.

### Minimal reproducible example
Call any endpoint with any DTO. That DTO is annotated by a custom constraint with a custom validator with an @Autowire dependency

### Expected behavior
The dependency is resolved and therefore not null

### Actual behavior
That dependency is not resolved according to Spring Spec

### Versions:
    - Vaadin / Hilla version: 1.2.10
    - Node version: 18.15.0
    - Java version: 1.8.0_352
    - Application Server (if applicable): Spring 2.7.0

### Working with spring
If you call a Spring service with org.springframework.validation.annotation.Validated and the same DTO as parameter with javax.validation.Valid [0] spring resolves the dependency as expected.

### Hibernate workaround
Hibernate has the same problem which we fixed by implementing a custom org.springframework.context.annotation.Configuration which returns a factory org.springframework.context.annotation.Bean that implements org.springframework.beans.factory.config.AutowireCapableBeanFactory

### Private Repo
As always we have shared a reproducer example in our private repo

[0]
@Validated
public class Service {
    public void serviceCall(@Valid final IEntity2 entity2) {

### PR DESCRIPTION
**Pull request by cromoteca**
The `EndpointInvoker` gets the Spring `ApplicationContext` as constructor parameter, so we can use the Spring Validator Bean instead of the explicit one.

Closes #964.

### CODE REVIEW

**Review by platosha — APPROVED** [review]

**Comment by cromoteca** [comment]
I see in the issue that you're using Hilla 1.2. That version is not maintained anymore. We can consider backporting down to 1.3 if that can help.

**Comment by gitgdako** [comment]
Hi. We are currently evaluating the possibility to upgrade to Hilla 2, but that might take some time. In the meanwhile we intend to use the latest stable 1.x, so making that feature available there would be of great use to us

**Comment by gitgdako** [comment]
Hi. In what 1.x version can we expect this to be included? We will be staying on 1.x (latest with regular upgrades) for a while

**Comment by platosha** [comment]
@gitgdako thanks for asking. Now that this change was [backported to the 1.3 branch](https://github.com/vaadin/hilla/pull/1034), it will be included in the next maintenance release, v1.3.15.

**Comment by gitgdako** [comment]
Code is working as expected in 1.3.15
Imo this issue is resolved

**Pull request merged**
