### PR TITLE
feat: always scan the root package of current module/project for endpoints

### LINKED ISSUE #994: Consider always scaning current project/module root package for endpoints
Currently, the packages from current project (or current module of a multi-module project) is scanned for endpoints, only if there is no configuration for the exposed packages from dependencies (or other modules). If the user configure the maven/gradle plugin to scan and include a single external endpoint from some dependency (e.g. SSO Kit), then they should also always list the a high-level package from the current project/module which is not convenient and redundant IMO.

Configuring the for exposed packages from other modules or from dependencies should not affect the parser behavior for scanning the packages in the current project (or current module of a multi-module project), as most of the times, the use case is to use some external utility endpoints, and not to hide the endpoints of the current project/module. 

We should consider always scanning the current project/module's packages, plus the additional exposed packages from the dependencies or other modules.

### PR DESCRIPTION
**Pull request by taefi**
## Description

This is a fixed-term solution for always including the root package of current module/project while scanning for endpoints.

Finding the root package of the current module can be done in different ways, and in this PR it is relying on the existence of a class annotated with `@SpringBootApplication`.

The better approach for scanning the endpoints could rely on spring beans instead, however, at the moment making such a breaking change is not possible, so until then, this can be considered as a partial solution.

Fixes #994

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

### CODE REVIEW

**Comment by Artur-** [comment]
Why are there quite a few pom.xml changes here? They don't seem to be related to the actual change

**Comment by taefi** [comment]
> Why are there quite a few pom.xml changes here? They don't seem to be related to the actual change

I had some random failures on CI showing symptoms of not performing prepare-frontend in dev-mode or the build-frontend in prod mode, so I added them in those modules.

**Comment by Artur-** [comment]
Can we make this only the Java code change  and see if the problems have been resolved by other PRs?

**Comment by taefi** [comment]
Updating this one was harder than creating a new PR. Closing in favor of #1453

**Pull request closed without merging**
